### ISSUE TITLE
Installation Guide Update

### ISSUE THREAD

**Issue by raiken-mf** [MrAntares/Ragna.roBrowser#23]
Hello there. There wasn't any other way to contact you direclty via mail so I opened a new issue.

The installation guide is outdated, there is ie. no api.html anymore. The build tools for compiling aren't there anymore. Also the index.php from the client folder is missing.

I was hoping to get roBrowser working, but seems impossible with the currently available installation guide.

Could you provide any help to set it up, please?

**Comment by wjrosa** [comment]
Hello!
You will still need those files. I guess they got removed due to copyright issues (that caused the original repository to be taken down). But I think you can still grab them there:
https://github.com/vthibault/roBrowser/

**Comment by MrAntares** [comment]
They are not neccessary for roBrowser to work, but added /api.html and tools/converter/index.html anyways. The client/index.php is already there.

fd610f19f46373790a59acadfed315562f630153
87e93e9509b694e769b1032665c8ae4ff5627051

**Comment by juliolitwin** [comment]
@MrAntares 
Which client version you recommend to use?

**Comment by cheffNFT** [comment]
there are no settings.js anymore.

**Comment by MrAntares** [comment]
@cheffNFT You are absolutely right, it is somewhat confuzing to get started, but really it is not that complicated. There are many options, but I never tried all of them only one. Out server uses websocket+wsproxy. It is the best method so far.
- You install and start the WSProxy on a port like myserver:5900, that points to the server's address that you use with a normal desktop client, like myserver:6900.
- You add your grfs and the DATA.INI (grf order) to the client/resources folder in robrowser and the clientinfo.xml (client-server information) to the client/data folder and if required set up the client/configs.php so that everything points to the right folder and file.
- You create a blank html with a DIV that has the ID "robrowser"
- You add a script that references the api.js
- You add a script that configures the roBrowser api with websocket+proxy and you provide all the addresses and settings, eg:
```
function initialize() {
				var ROConfig = {
					target:        document.getElementById("robrowser"),
					type:          ROBrowser.TYPE.FRAME,
					application:   ROBrowser.APP.ONLINE,
					remoteClient:  "http://yourserver/client/",
					servers: 'data/clientinfo.xml',
					socketProxy: 'ws://yourserver:5900',
					development:    true,
					packetver: 20120410
				};
				var RO = new ROBrowser(ROConfig);
				RO.start();
			}
```

- and finally call the initialize after the page loads at the end of your script tag:
```
window.addEventListener("load", function(){ 
					initialize();
				}, false);
```

That is all.
Unfortunately, you need to understand a bit how this whole stuff works on client and server side and a bit of HTML/JavaScript to make it work, because there are many things you can configure, but you can always peek from a working example, just like I did from the original roBrowser test server.

**Comment by waken22** [comment]
I'm gonna point out my experience, because i think it could be useful for a future detailed guide.

If you are having problems to login to map-server consider the following steps:

1- Disable pincode.
2- Disable packet_obfuscation. (no idea if this is supported out of the box by robrowser using Packet Encryption)
3- If you are using wsproxy (in windows) i needed to press enter to make it work, it's weird but it happened to me.

And if robrowser is not loading the resources, please, open the network chrome tab and check if the path is correct or not, and then modify `ROConfig.remoteClient` accordingly.

**Comment by waken22** [comment]
And another reminder, for remote client yes, it's kinda obvious but you are gonna need a web server (apache using xamp, lamp) or whatever to serve the php files.
